from flask import Flask, render_template, jsonify
import json
import os

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/api/data')
def get_data():
    try:
        # Read the JSON file generated by your C executable
        with open('simulation_data.json', 'r') as file:
            data = json.load(file)
        return jsonify(data)
    except FileNotFoundError:
        return jsonify({"error": "simulation_data.json not found. Run the C code first!"}), 404

if __name__ == '__main__':
    print("\n🚀 Starting CSEN601 Pipeline Visualizer...")
    print("👉 Open your browser to: http://127.0.0.1:5000\n")
    app.run(debug=True)